<?php
// $Id: activitystream_lastfm.module,v 1.1.4.2 2008/07/31 17:05:27 akalsey Exp $

/**
 * @file
 * The module for importing LastFM activity.
 */

/*
 * The API passes in a $user object that contains four properties:
 * uid, userid, password, feed. These properties contain the account
 * information entered into the user's settings page, along with the 
 * uid of their Drupal account.
 */
function activitystream_lastfm_streamapi($user) {
  // This user doesn't have a lastfm ID entered
  if (!$user->userid) {
    return;
  }
  
  // Use the activitystream_feed module to pull in the user's
  // history. 
  $user->feed = 'http://ws.audioscrobbler.com/1.0/user/'. $user->userid .'/recenttracks.rss';
  $items = activitystream_feed_streamapi($user);
  return $items;
}


/*
 * Implement a user settings form hook. Modules should build a form
 * using an array that mirrors the Drupal form API. activitystream.module
 * will add the form elements to a tab called Activity Streams on the
 * user's Profile Edit page. Fields should be named
 * yourmodulename_fieldname. For instance, to store the user ID for 
 * Flickr, the field name is activitystream_flickr_userid
 *
 * To avoid collisions with other activitystream module's forms
 * use your module's name as the form array's key.
 *
 * @param $edit
 *   The values of the form fields, used for setting defaults
 * 
 */
function activitystream_lastfm_activitystream_settings(&$edit) {
  $form['activitystream_lastfm'] = array(
      '#type' => 'fieldset',
      '#title' => t('lastfm settings'));
  $form['activitystream_lastfm']['activitystream_lastfm_userid'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => empty($edit['activitystream_lastfm_userid']) ? '' : $edit['activitystream_lastfm_userid'],
    '#description' => t('The username for your lastfm account'));
  return $form;  
}

function theme_activitystream_lastfm_icon() {
  return theme_image(drupal_get_path('module', 'activitystream_lastfm') .'/lastfm.png', 'Last.fm');
}

function theme_activitystream_lastfm_item($activity) {
  $node = node_load($activity->nid);
  $date = theme('activitystream_date', $node->created);
  $user = user_load(array('uid' => $node->uid));
  $name = theme('activitystream_username', $user);
  return '<span class="activitystream-item">'. theme('activitystream_lastfm_icon') ." <span>$name listened to ". l($node->title, $activity->link) ." <span class=\"activitystream-created\">$date</span></span>". l('#', 'node/'. $node->nid, array('class' => 'permalink')) .'</span>';
}

function activitystream_lastfm_theme() {
  return array(
    'activitystream_lastfm_icon' => array(
      'arguments' => array(),
    ),
    'activitystream_lastfm_item' => array(
      'arguments' => array('activity' => NULL),
    ),
  );
}