<?php
// $Id: activitystream_delicious.module,v 1.2.2.2 2008/07/31 17:05:26 akalsey Exp $
/**
 * @file
 * The module for importing del.icio.us links
 */
 
/*
 * The API passes in a $user object that contains four properties:
 * uid, userid, password, feed. These properties contain the account
 * information entered into the user's settings page, along with the 
 * uid of their Drupal account.
 */
function activitystream_delicious_streamapi($user) {
  // This user doesn't have a Delicious ID entered
  // into their settings. Move along. Nothing
  // to see here.
  if (!$user->userid) {
    return;
  }
  
  // Use the activitystream_feed module to pull in the user's
  // del.icio.us links
  $user->feed = 'http://del.icio.us/rss/'. $user->userid;
  $items = activitystream_feed_streamapi($user);
  return $items;
}


/*
 * Implement a user settings form hook. Modules should build a form
 * using an array that mirrors the Drupal form API. activitystream.module
 * will add the form elements to a tab called Activity Streams on the
 * user's Profile Edit page. Fields should be named
 * yourmodulename_fieldname. For instance, to store the user ID for 
 * Flickr, the field name is activitystream_flickr_userid
 *
 * To avoid collisions with other activitystream module's forms
 * use your module's name as the form array's key.
 *
 * @param $edit
 *   The values of the form fields, used for setting defaults
 * 
 */
function activitystream_delicious_activitystream_settings(&$edit) {
  $form['activitystream_delicious'] = array(
      '#type' => 'fieldset',
      '#title' => t('Del.icio.us settings'));
  $form['activitystream_delicious']['activitystream_delicious_userid'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => empty($edit['activitystream_delicious_userid']) ? '' : $edit['activitystream_delicious_userid'],
    '#description' => t('The username for your Del.icio.us account'));
  return $form;  
}

function theme_activitystream_delicious_icon() {
  return theme_image(drupal_get_path('module', 'activitystream_delicious') .'/delicious.png', 'Del.icio.us');
}

function theme_activitystream_delicious_item($action) {
  $node = node_load($action->nid);
  $date = theme('activitystream_date', $node->created);
  $user = user_load(array('uid' => $node->uid));
  $name = theme('activitystream_username', $user);
  return '<span class="activitystream-item">'. theme('activitystream_delicious_icon') ." <span>$name linked to ". l($node->title, $action->link) ." <span class=\"activitystream-created\">$date</span></span>". l('#', 'node/'. $node->nid, array('attributes' => array('class' => 'permalink'))) .'</span>';
}

function activitystream_delicious_theme() {
  return array(
    'activitystream_delicious_icon' => array(
      'arguments' => array(),
    ),
    'activitystream_delicious_item' => array(
      'arguments' => array('action' => NULL),
    ),
  );
}